import { PhoneSpec, NewsArticle } from './types';

const basePhones: PhoneSpec[] = [
  {
    id: 'iphone-15-pro',
    brand: 'Apple',
    model: 'iPhone 15 Pro',
    releaseDate: '2023-09-22',
    price: 999,
    currency: 'USD',
    availability: 'Available',
    displaySize: 6.1,
    displayResolution: '2556 x 1179',
    displayType: 'OLED',
    displayRefreshRate: 120,
    displayProtection: 'Ceramic Shield',
    displayPPI: 460,
    displayAspectRatio: '19.5:9',
    displayBrightness: 2000,
    displayHDR: true,
    displayAlwaysOn: true,
    chipset: 'Apple A17 Pro',
    cpu: 'Hexa-core',
    gpu: 'Apple GPU (6-core)',
    ram: [8],
    storage: [128, 256, 512, 1024],
    expandableStorage: false,
    maxExpandableStorage: 0,
    mainCameraMP: 48,
    mainCameraAperture: 'f/1.8',
    mainCameraSensorSize: '1/1.28"',
    mainCameraPixelSize: 1.22,
    mainCameraOIS: true,
    ultrawideCameraMP: 12,
    ultrawideAperture: 'f/2.2',
    ultrawideFOV: 120,
    telephotoCamera: 12,
    telephotoAperture: 'f/2.8',
    telephotoZoom: '3x optical',
    telephotoOIS: true,
    depthSensor: false,
    macroCamera: 0,
    videoRecording: ['4K@60fps', '1080p@240fps'],
    videoStabilization: 'Sensor-shift OIS',
    nightMode: true,
    proMode: true,
    hdr: true,
    panorama: true,
    slowMotion: '1080p@240fps',
    timelapseMode: true,
    frontCameraMP: 12,
    frontCameraAperture: 'f/1.9',
    frontCameraVideo: '4K@60fps',
    frontCameraHDR: true,
    batteryCapacity: 3274,
    batteryType: 'Li-Ion',
    fastCharging: 27,
    wirelessCharging: 15,
    reverseCharging: false,
    batteryLife: 'Up to 23 hours video',
    network5G: true,
    network4G: true,
    network3G: true,
    network2G: true,
    wifiStandards: ['Wi-Fi 6E'],
    bluetooth: '5.3',
    nfc: true,
    infrared: false,
    usbType: 'USB-C',
    usbVersion: 'USB 3.2',
    headphoneJack: false,
    dimensions: { height: 146.6, width: 70.6, thickness: 8.25 },
    weight: 187,
    buildMaterials: {
      front: 'Ceramic Shield glass',
      back: 'Textured matte glass',
      frame: 'Titanium'
    },
    colors: ['Natural Titanium', 'Blue Titanium', 'White Titanium', 'Black Titanium'],
    ipRating: 'IP68',
    os: 'iOS',
    osVersion: '17',
    ui: 'iOS',
    updatePolicy: '5+ years',
    speakers: 'Stereo',
    audioFeatures: ['Spatial audio', 'Dolby Atmos'],
    fingerprint: 'None',
    faceUnlock: true,
    accelerometer: true,
    gyroscope: true,
    proximity: true,
    compass: true,
    barometer: true,
    dualSIM: true,
    simType: 'Nano-SIM and eSIM',
    images: ['/phones/iphone-15-pro.jpg'],
    videos: [],
    rating: 4.7,
    reviewCount: 1250,
    createdAt: '2023-09-22T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z',
    featured: true,
    trending: true,
    latestLaunch: false
  },
  {
    id: 'samsung-s24-ultra',
    brand: 'Samsung',
    model: 'Galaxy S24 Ultra',
    releaseDate: '2024-01-24',
    price: 1199,
    currency: 'USD',
    availability: 'Available',
    displaySize: 6.8,
    displayResolution: '3120 x 1440',
    displayType: 'Dynamic AMOLED 2X',
    displayRefreshRate: 120,
    displayProtection: 'Gorilla Armor',
    displayPPI: 505,
    displayAspectRatio: '19.3:9',
    displayBrightness: 2600,
    displayHDR: true,
    displayAlwaysOn: true,
    chipset: 'Snapdragon 8 Gen 3',
    cpu: 'Octa-core',
    gpu: 'Adreno 750',
    ram: [12],
    storage: [256, 512, 1024],
    expandableStorage: false,
    maxExpandableStorage: 0,
    mainCameraMP: 200,
    mainCameraAperture: 'f/1.7',
    mainCameraSensorSize: '1/1.3"',
    mainCameraPixelSize: 0.6,
    mainCameraOIS: true,
    ultrawideCameraMP: 12,
    ultrawideAperture: 'f/2.2',
    ultrawideFOV: 120,
    telephotoCamera: 50,
    telephotoAperture: 'f/3.4',
    telephotoZoom: '5x optical',
    telephotoOIS: true,
    depthSensor: false,
    macroCamera: 0,
    videoRecording: ['8K@30fps', '4K@120fps'],
    videoStabilization: 'OIS + EIS',
    nightMode: true,
    proMode: true,
    hdr: true,
    panorama: true,
    slowMotion: '1080p@240fps',
    timelapseMode: true,
    frontCameraMP: 12,
    frontCameraAperture: 'f/2.2',
    frontCameraVideo: '4K@60fps',
    frontCameraHDR: true,
    batteryCapacity: 5000,
    batteryType: 'Li-Ion',
    fastCharging: 45,
    wirelessCharging: 15,
    reverseCharging: true,
    batteryLife: 'Up to 30 hours video',
    network5G: true,
    network4G: true,
    network3G: true,
    network2G: true,
    wifiStandards: ['Wi-Fi 7'],
    bluetooth: '5.3',
    nfc: true,
    infrared: false,
    usbType: 'USB-C',
    usbVersion: 'USB 3.2',
    headphoneJack: false,
    dimensions: { height: 162.3, width: 79.0, thickness: 8.6 },
    weight: 232,
    buildMaterials: {
      front: 'Gorilla Armor',
      back: 'Gorilla Glass Victus 2',
      frame: 'Titanium'
    },
    colors: ['Titanium Gray', 'Titanium Black', 'Titanium Violet', 'Titanium Yellow'],
    ipRating: 'IP68',
    os: 'Android',
    osVersion: '14',
    ui: 'One UI 6.1',
    updatePolicy: '7 years',
    speakers: 'Stereo',
    audioFeatures: ['Dolby Atmos', 'AKG tuning'],
    fingerprint: 'Ultrasonic under display',
    faceUnlock: true,
    accelerometer: true,
    gyroscope: true,
    proximity: true,
    compass: true,
    barometer: true,
    dualSIM: true,
    simType: 'Nano-SIM and eSIM',
    images: ['/phones/samsung-s24-ultra.jpg'],
    videos: [],
    rating: 4.8,
    reviewCount: 980,
    createdAt: '2024-01-24T00:00:00Z',
    updatedAt: '2024-02-15T00:00:00Z',
    featured: true,
    trending: true,
    latestLaunch: true
  }
];

export const mockPhones: PhoneSpec[] = [
  ...basePhones,
  ...basePhones.map((p, i) => ({ ...p, id: `${p.id}-dup1-${i}`, trending: true, featured: false, latestLaunch: false })),
  ...basePhones.map((p, i) => ({ ...p, id: `${p.id}-dup2-${i}`, trending: false, featured: true, latestLaunch: false })),
  ...basePhones.map((p, i) => ({ ...p, id: `${p.id}-dup3-${i}`, trending: false, featured: false, latestLaunch: true })),
  ...basePhones.map((p, i) => ({ ...p, id: `${p.id}-dup4-${i}`, trending: true, featured: true, latestLaunch: false })),
  ...basePhones.map((p, i) => ({ ...p, id: `${p.id}-dup5-${i}`, trending: true, featured: false, latestLaunch: true })),
  ...basePhones.map((p, i) => ({ ...p, id: `${p.id}-dup6-${i}`, trending: false, featured: true, latestLaunch: true })),
  ...basePhones.map((p, i) => ({ ...p, id: `${p.id}-dup7-${i}`, trending: true, featured: true, latestLaunch: true })),
  ...basePhones.map((p, i) => ({ ...p, id: `${p.id}-dup8-${i}`, trending: true, featured: false, latestLaunch: false })),
  ...basePhones.map((p, i) => ({ ...p, id: `${p.id}-dup9-${i}`, trending: false, featured: true, latestLaunch: false })),
];

export const mockNews: NewsArticle[] = [
  {
    id: 'news-1',
    title: 'Samsung Galaxy S25 Series: Everything We Know So Far',
    slug: 'samsung-galaxy-s25-series-everything-we-know',
    category: 'Rumors',
    excerpt: 'The Samsung Galaxy S25 series is expected to launch in early 2025 with major upgrades.',
    content: 'Full article content here...',
    image: '/news/samsung-s25.jpg',
    author: 'Tech Editor',
    publishedAt: '2024-11-10T10:00:00Z',
    updatedAt: '2024-11-10T10:00:00Z',
    published: true,
    tags: ['Samsung', 'Galaxy S25', 'Rumors']
  },
  {
    id: 'news-2',
    title: 'iPhone 16 Pro Max Review: Apple\'s Best Yet',
    slug: 'iphone-16-pro-max-review',
    category: 'Reviews',
    excerpt: 'We spent two weeks with the iPhone 16 Pro Max. Here\'s our full review.',
    content: 'Full article content here...',
    image: '/news/iphone-16-pro.jpg',
    author: 'Tech Editor',
    publishedAt: '2024-11-09T14:00:00Z',
    updatedAt: '2024-11-09T14:00:00Z',
    published: true,
    tags: ['Apple', 'iPhone 16', 'Review']
  }
];
